# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mydoctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_analyze', models.CharField(max_length=60, verbose_name='Название анализа')),
                ('date_of_completion', models.DateTimeField(verbose_name='Дата прохождения анализа')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 423535, tzinfo=utc), verbose_name='Дата синхронизации')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoctor.Patient', verbose_name='Пациент')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_procedure', models.CharField(max_length=60, verbose_name='Название процедуры')),
                ('date_of_completion', models.DateTimeField(verbose_name='Дата выполнения процедуры')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 424536, tzinfo=utc), verbose_name='Дата синхронизации')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoctor.Patient', verbose_name='Пациент')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doctor', models.CharField(max_length=60, verbose_name='Название доктора')),
                ('date_of_completion', models.DateTimeField(verbose_name='Дата визита к врачу')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 424035, tzinfo=utc), verbose_name='Дата синхронизации')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoctor.Patient', verbose_name='Пациент')),
            ],
        ),
        migrations.CreateModel(
            name='TakenMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_medicine', models.CharField(max_length=60, verbose_name='Название медикамента')),
                ('number_of_necessary_medicine', models.IntegerField(verbose_name='Количество медикаметов которые необходимо принять')),
                ('number_of_medication_taken', models.IntegerField(verbose_name='Количество принятых медикаметов')),
                ('date_of_taking_medicine', models.DateField(verbose_name='Дата принятия медикатов')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 422535, tzinfo=utc), verbose_name='Дата синхронизации')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoctor.Patient', verbose_name='Пациент')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
            ],
        ),
    ]
