# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 417030, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название анализа')),
                ('description', models.CharField(max_length=200, verbose_name='Описание анализа')),
                ('date_appointment', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 419032, tzinfo=utc), verbose_name='Дата назначения')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название препарата')),
                ('type', models.CharField(max_length=60, verbose_name='Тип медикамента')),
                ('method_reception', models.CharField(max_length=60, verbose_name='Способ приёма')),
                ('start_date', models.DateField(verbose_name='Дата начала приёма')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('dosage', models.CharField(max_length=20, verbose_name='Дозировка')),
                ('number_medicines', models.IntegerField(verbose_name='Количество')),
                ('number_of_receptions_per_day', models.IntegerField(verbose_name='Количество применений в день')),
                ('description', models.CharField(max_length=200, verbose_name='Дополнительная информация')),
                ('after_meals', models.CharField(choices=[('Независимо', 'Независимо'), ('До еды', 'До еды'), ('После еды', 'После еды'), ('Во время еды', 'Во время еды')], max_length=20, verbose_name='До еды?')),
                ('date_appointment', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 420032, tzinfo=utc), verbose_name='Дата назначения')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('insurance_number', models.CharField(max_length=20, unique=True, verbose_name='Номер страхового полиса')),
                ('DOB', models.DateField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 418031, tzinfo=utc), verbose_name='Дата рождения')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 418031, tzinfo=utc), verbose_name='Дата регистрации')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название процедуры')),
                ('description', models.CharField(max_length=200, verbose_name='Дополнительная информация')),
                ('number', models.IntegerField(verbose_name='Количество процедур')),
                ('date_appointment', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 421034, tzinfo=utc), verbose_name='Дата назначения')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoctor.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doctor', models.CharField(max_length=60, verbose_name='Тип врача')),
                ('description', models.CharField(max_length=200, verbose_name='Дополнительная информация')),
                ('date_appointment', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 22, 24, 11, 419532, tzinfo=utc), verbose_name='Дата назначения')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoctor.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoctor.Patient'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydoctor.Patient'),
        ),
    ]
